config/routes.rb
Board::Application.routes.draw do
  resources :comments

  resources :tickets

  resources :projects

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :content, :creator_id, :description, :owner_id, :project_id, :title
  belongs_to :project
  belongs_to :creator,:class_name => "User", :foreign_key => "creator_id"
  belongs_to :owner, :class_name => "User", :foreign_key => "owner_id"
  has_many :comments
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :authenticate_user!
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tickets }
    end
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/new
  # GET /tickets/new.json
  def new
    @ticket = Ticket.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ticket }
    end
  end

  # GET /tickets/1/edit
  def edit
    @ticket = Ticket.find(params[:id])
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(params[:ticket])

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render json: @ticket, status: :created, location: @ticket }
      else
        format.html { render action: "new" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tickets/1
  # PUT /tickets/1.json
  def update
    @ticket = Ticket.find(params[:id])

    respond_to do |format|
      if @ticket.update_attributes(params[:ticket])
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket = Ticket.find(params[:id])
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.haml
= simple_form_for(@ticket) do |f|
  = f.error_notification

  .form-inputs
    = f.select :project_id , current_user.projects.collect {|p| [ p.title, p.id ] }
    = f.input :title
    = f.input :description
    = f.input :content
    = f.hidden_field :creator_id, :value => current_user.id
    = f.hidden_field :owner_id, :value => current_user.id

  .form-actions
    = f.button :submit

app/views/tickets/edit.html.haml
%h1 Editing ticket

= render 'form'

= link_to 'Show', @ticket
\|
= link_to 'Back', tickets_path

app/views/tickets/index.html.haml
.row-fluid
  .span12
    .well
      .navbar.navbar-heading
        .navbar-inner
          .container{:style => "width: auto;"}
            %a.brand{:href => "#"}  tickets
      %table.table.table-bordered.table-striped.small-font
        %tr
          %th Title
          %th Description
          %th Content
          %th Creator
          %th Owner
          %th Project
          %th
          %th
          %th

        - @tickets.each do |ticket|
          %tr
            %td= ticket.title
            %td= ticket.description
            %td= ticket.content
            %td= ticket.creator_id
            %td= ticket.owner_id
            %td= ticket.project_id
            %td= link_to 'Show', ticket
            %td= link_to 'Edit', edit_ticket_path(ticket)
            %td= link_to 'Destroy', ticket, :confirm => 'Are you sure?', :method => :delete

      %br

      = link_to 'New Ticket', new_ticket_path

app/views/tickets/new.html.haml
%h1 New ticket

= render 'form'

= link_to 'Back', tickets_path

app/views/tickets/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @ticket.title
%p
  %b Description:
  = @ticket.description
%p
  %b Content:
  = @ticket.content
%p
  %b Creator:
  = @ticket.creator_id
%p
  %b Owner:
  = @ticket.owner_id
%p
  %b Project:
  = @ticket.project_id

= link_to 'Edit', edit_ticket_path(@ticket)
\|
= link_to 'Back', tickets_path